<?php

/**
 * Implements hook_og_tasks_info().
 */
function vsite_preset_og_tasks_info($entity_type, $entity) {
  $tasks = array();

  $tasks['AcademicsSection'] = new vsiteTaskAcademicsSection($entity_type, $entity);
  $tasks['ResearchSection'] = new vsiteTaskResearchSection($entity_type, $entity);
  $tasks['ResourcesSection'] = new vsiteTaskResourcesSection($entity_type, $entity);
  $tasks['NewsEventsSection'] = new vsiteTaskNewsEventsSection($entity_type, $entity);
  $tasks['AboutSection'] = new vsiteTaskAboutSection($entity_type, $entity);
  $tasks['ContactPage'] = new vsiteTaskContactPage($entity_type, $entity);

  // @fixme determine best level of granularity
  $title = t('News & Events');
  $body = t('Coming soon!');
  $weight = 99;
  $tasks['NewsEventsSection'] = new vsite_add_section_task($entity_type, $entity, $title, $weight, $body);
  return $tasks;
}

/**
 * Implements hook_spaces_presets().
 */
function vsite_preset_spaces_preset() {
  $export = array();

  $preset = new stdClass();
  $preset->disabled = FALSE; /* Edit this to true to make a default spaces_presets disabled initially */
  $preset->api_version = 3;
  $preset->name = 'os_department';
  $preset->title = 'OS Department - Academic';
  $preset->description = '';
  $preset->space_type = 'og';
  $preset->value = array(
    'bundles' => array('department'),
    'og_tasks' => array(
      'vsiteTaskAcademicsSection',
      'vsiteTaskResearchSection',
      'vsiteTaskResourcesSection',
      'vsiteTaskNewsEventsSection',
      'vsiteTaskAboutSection',
      'vsiteTaskContactPage',
    ),
    'variable' => array(
      'spaces_features' => array(
        'os' => '1',
        'os_pages' => '1',
        'os_classes' => '1',
        'os_news' => '1',
        'os_events' => '1',
        'os_profiles' => '1',
        'os_links' => '1',
      ),
      'spaces_features_available' => array(
        'os_blog',
        'os_booklets',
        'os_classes',
        'os_dataverse',
        'os_events',
        'os_faq',
        'os_files_private',
        'os_image_gallery',
        'os_links',
        'os_news',
        'os_pages',
        'os_presentations',
        'os_profiles',
        'os_publications',
        'os_reader',
        'os_software',
        'harvard_courses',
      ),
      'site_frontpage' => 'home',
      'theme_default' => 'hwpi_classic',
      'os_menus' => array(
        'primary-menu' => 'Primary Menu',
        'secondary-menu' => 'Secondary Menu',
        'quick_links' => 'Quick Links',
      ),
      'os_appearance_hwpi_classic_flavor' => 'default',
    ),
    'menus' => array(
      'primary-menu' => array(
        1472 => array(
          'link_path' => 'home',
          'menu_name' => 'primary-menu',
          'link_title' => 'HOME',
          'options' => array(),
          'external' => 0,
          'weight' => -90,
          'hidden' => 0,
          'has_children' => 0,
          'expanded' => 0,
          'module' => 'menu',
          'customized' => 0,
          'updated' => 0,
          'mlid' => 1472,
          'plid' => 0,
          'p1' => 1472,
          'p2' => 0,
          'p3' => 0,
          'p4' => 0,
          'p5' => 0,
          'p6' => 0,
          'p7' => 0,
          'p8' => 0,
          'p9' => 0,
          'depth' => 1,
          'router_path' => 'home',
        ),
        1452 => array(
          'link_path' => 'people',
          'menu_name' => 'primary-menu',
          'link_title' => 'People',
          'options' => array(),
          'external' => 0,
          'weight' => '3',
          'hidden' => 0,
          'has_children' => 0,
          'expanded' => 0,
          'module' => 'menu',
          'customized' => 0,
          'updated' => 0,
          'mlid' => 1452,
          'plid' => 0,
          'p1' => 1452,
          'p2' => 0,
          'p3' => 0,
          'p4' => 0,
          'p5' => 0,
          'p6' => 0,
          'p7' => 0,
          'p8' => 0,
          'p9' => 0,
          'depth' => 1,
          'router_path' => 'people',
        ),
      ),
      'quick_links' => array(
      ),
    ),
    'context' => array(
      'os_public:reaction:block' => array(
        'blocks' => array(
          'os-quick_links' => array(
            'module' => 'os',
            'delta' => 'quick_links',
            'cache' => -1,
            'region' => 'header_third',
            'status' => 0,
            'title' => '',
            'weight' => 0,
          ),
          'boxes-site_info' => array(
            'module' => 'boxes',
            'delta' => 'site_info',
            'region' => 'header_second',
            'weight' => 0,
            'status' => 0,
            'title' => '',
          ),
          'os-primary-menu' => array(
            'module' => 'os',
            'delta' => 'primary-menu',
            'region' => 'menu_bar',
            'weight' => 0,
            'status' => 0,
            'title' => '',
          ),
          'boxes-academic-footer-left' => array(
            'module' => 'boxes',
            'delta' => 'academic-footer-left',
            'title' => 'Footer Left Text',
            'region' => 'footer_first',
            'status' => 0,
            'weight' => 0,
          ),
        ),
      ),
    ),
    'boxes' => array(
      'academic-footer-left' => (object) array(
        'changed' => NULL,
        'delta' => 'academic-footer-left',
        'title' => '',
        'description' => 'Footer Left Text',
        'options' => array (
          'text' => array (
            'value' => '<p>LOGO</p><p style="padding-left: 30px;">12 Your Street<br>Cambridge, MA 00000<br>Tel (xxx) xxx-xxxx</p>',
            'format' => 'filtered_html',
          ),
          'format' => 1,
          'additional_classes' => '',
        ),
        'plugin_key' => 'os_boxes_html',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('OS Department - Academic');
  $export['os_department'] = $preset;

  return $export;
}